theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.gutters]
layout=["diagnostics"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
F9 = [
  ":insert-output echo ///////////////////////////////////",
  "open_below",
  ":insert-output echo /////~ ",
  "insert_at_line_end",]
F4 = ":run-shell-command run.bat"

[keys.insert]
j = { j = "normal_mode" }
