theme = "aaaa";

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.gutters]
layout=["diagnostics"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
F9 = [
  ":insert-output echo ///////////////////////////////////",
  "open_below",
  ":insert-output echo /////~ ",
  "insert_at_line_end",]
  
F1 = [":insert-output echo // NOTE(bchui): ", "insert_at_line_end",]
F2 = [":insert-output echo // TODO(bchui): ", "insert_at_line_end",]
F4 = ":run-shell-command run.bat"

F8 = ["select_regex", "align_selections", "merge_selections"]


"g" = { "D" = ["vsplit", "jump_view_up", "goto_definition"] }

[keys.insert]
j = { j = "normal_mode" }
