# Define the language server configuration for clangd (used by both C and C++)
#[language-server.clangd]
#command = "clangd"
#args = ["--experimental-modules-support"]

# Define the language server configuration for Zig
[language-server.zls]
command = "zls"

# C Language Configuration
[[language]]
name = "c"
file-types = ["c", "h"]  # Extensions for C files
auto-format = true       # Format on save
language-servers = ["clangd"]  # Reference the clangd language server
formatter = { command = "clang-format", args = ["--assume-filename", "$FILEPATH", "-style=file"] }


# C++ Language Configuration
[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "h", "cxx", "cc", "cppm"]  # Extensions for C++ files
auto-format = true       # Format on save
language-servers = ["clangd"]  # Reference the clangd language server
formatter = { command = "clang-format", args = ["--assume-filename", "$FILEPATH", "-style=file"] }


# Zig Language Configuration
[[language]]
name = "zig"
file-types = ["zig"]  # Extensions for Zig files
auto-format = true    # Format on save
language-servers = ["zls"]  # Reference the zls language server
formatter = { command = "zig", args = ["fmt", "--stdin"] }

# Svelte
[[language]]
name = "svelte"
language-servers = [
  "emmet-ls",
  "svelteserver",
  "typescript-language-server",
  "tailwindcss-lannguage-server",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "eslint-language-server",
  "typescript-language-server",
  "tailwindcss-ls",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "emmet-ls",
  "typescript-language-server",
  "tailwindcss-lannguage-server",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true


[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"


[[language]]
name = "wren"
file-types = ["wren"]
auto-format = true

[[language]]
name = "ocaml"
scope = "source.ocaml"
file-types = ["ml"]
language-servers = ["ocamllsp"]
auto-format = true

[language.formatter]
command = "ocamlformat"
args = ["--name", "*.ml", "-"]

# -----------------------------------------------

[[language]]
name = "ocaml.interface"
scope = "source.ocaml.interface"
file-types = ["mli"]
language-servers = ["ocamllsp"]
auto-format = true

[language.formatter]
command = "ocamlformat"
args = ["--name", "*.mli", "-"]