# C Language Configuration
[[language]]
name = "c"
file-types = ["c", "h"]
auto-format = true
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--assume-filename", "$FILEPATH", "-style=file"] }

# C++ Language Configuration
[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "h", "cxx", "cc", "cppm"]
auto-format = true
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--assume-filename", "$FILEPATH", "-style=file"] }

# Zig Language Configuration
[[language]]
name = "zig"
file-types = ["zig"]
auto-format = true
language-servers = ["zls"]
formatter = { command = "zig", args = ["fmt", "--stdin"] }

# Svelte Language Configuration
[[language]]
name = "svelte"
language-servers = [
  "emmet-ls",
  "svelteserver",
  "typescript-language-server",
  "tailwindcss-ls", # CORRECTED: Removed typo and duplicate
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

# TypeScript Language Configuration
[[language]]
name = "typescript"
language-servers = [
  "eslint-language-server",
  "typescript-language-server",
  "tailwindcss-ls",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

# TSX Language Configuration
[[language]]
name = "tsx"
language-servers = [
  "emmet-ls",
  "typescript-language-server",
  "tailwindcss-ls", # CORRECTED: Removed typo and duplicate
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "tsx"] }
auto-format = true

# Wren Language Configuration
[[language]]
name = "wren"
file-types = ["wren"]
auto-format = true

# OCaml Language Configuration
[[language]]
name = "ocaml"
scope = "source.ocaml"
file-types = ["ml"]
language-servers = ["ocamllsp"]
auto-format = true
formatter = { command = "ocamlformat", args = ["--name", "*.ml", "-"] }

# OCaml Interface Language Configuration
[[language]]
name = "ocaml.interface"
scope = "source.ocaml.interface"
file-types = ["mli"]
language-servers = ["ocamllsp"]
auto-format = true
formatter = { command = "ocamlformat", args = ["--name", "*.mli", "-"] }

# --- Language Server Specific Settings ---
[language-server.zls]
command = "zls"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"